### PR TITLE
Remove need for bare-io by using encode_utf8

### LINKED ISSUE #34: Fails to build with no_std since all versions of `bare-io` were yanked
One solution could be to just remove the no_std feature. It doesn't seem to be actually *exposed* anywhere other than writing to a `&mut &mut [u8]`, and that can be trivially replaced.

I'll fix this.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #34 

This makes the no_std feature completely obsolete, but it needs to be kept for compatibility (unless a major version bump is done).

There shouldn't be any MSRV concerns as encode_utf8 was stable in 1.15, the MSRV for this crate is at least 1.31 since it uses edition 2018.

### CODE REVIEW

**Comment by ghost** [comment]
Ran the benchmarks (once)

Before:

```
test benches::bench_inlinable_string_from_large                ... bench:          33 ns/iter (+/- 2)
test benches::bench_inlinable_string_from_small                ... bench:           2 ns/iter (+/- 0)
test benches::bench_inlinable_string_push_str_large_onto_empty ... bench:          44 ns/iter (+/- 1)
test benches::bench_inlinable_string_push_str_large_onto_large ... bench:         146 ns/iter (+/- 3)
test benches::bench_inlinable_string_push_str_small_onto_empty ... bench:           2 ns/iter (+/- 0)
test benches::bench_inlinable_string_push_str_small_onto_small ... bench:          10 ns/iter (+/- 0)
test benches::bench_std_string_from_large                      ... bench:          32 ns/iter (+/- 2)
test benches::bench_std_string_from_small                      ... bench:          13 ns/iter (+/- 0)
test benches::bench_std_string_push_str_large_onto_empty       ... bench:          41 ns/iter (+/- 0)
test benches::bench_std_string_push_str_large_onto_large       ... bench:         148 ns/iter (+/- 3)
test benches::bench_std_string_push_str_small_onto_empty       ... bench:          24 ns/iter (+/- 0)
test benches::bench_std_string_push_str_small_onto_small       ... bench:          39 ns/iter (+/- 1)
test inline_string::benches::its_fast                          ... bench:           0 ns/iter (+/- 0)
```

After:

```
test benches::bench_inlinable_string_from_large                ... bench:          33 ns/iter (+/- 1)
test benches::bench_inlinable_string_from_small                ... bench:           2 ns/iter (+/- 0)
test benches::bench_inlinable_string_push_str_large_onto_empty ... bench:          44 ns/iter (+/- 0)
test benches::bench_inlinable_string_push_str_large_onto_large ... bench:         147 ns/iter (+/- 3)
test benches::bench_inlinable_string_push_str_small_onto_empty ... bench:           2 ns/iter (+/- 0)
test benches::bench_inlinable_string_push_str_small_onto_small ... bench:          10 ns/iter (+/- 0)
test benches::bench_std_string_from_large                      ... bench:          31 ns/iter (+/- 1)
test benches::bench_std_string_from_small                      ... bench:          13 ns/iter (+/- 0)
test benches::bench_std_string_push_str_large_onto_empty       ... bench:          36 ns/iter (+/- 2)
test benches::bench_std_string_push_str_large_onto_large       ... bench:         150 ns/iter (+/- 2)
test benches::bench_std_string_push_str_small_onto_empty       ... bench:          18 ns/iter (+/- 1)
test benches::bench_std_string_push_str_small_onto_small       ... bench:          29 ns/iter (+/- 1)
test inline_string::benches::its_fast                          ... bench:           0 ns/iter (+/- 0)
```

I have no idea what that `bench_std_string_push_str_small_onto_small` difference means.

**Comment by ArtemGr** [comment]
Thanks! Would you bump to `version = "0.1.15"`?

**Comment by ghost** [comment]
There's also a `miri` failure when running with -Zmiri-tag-raw-pointers, so I'd ideally get that fixed before a release. I'll make a different branch for that (based off this PR because I can't get the code to build without it).

**Comment by ghost** [comment]
Scratch that, I'll just make the fix here, it shouldn't be too major.

**Review by ArtemGr — APPROVED** [review]

**Comment by ArtemGr** [comment]
Awesome!

**Comment by ArtemGr** [comment]
In case somebody's looking for `bare-io`, looks like it has been renamed to `core2`, https://github.com/technocreatives/core2/commit/4072d2a09ba0d656571b1cd2ef6d95aa575c4a69.

**Pull request merged**
